### ISSUE TITLE
Can't extend Teng::Row by specifying "row_class".

### ISSUE THREAD

**Issue by key-amb** [nekokak/p5-Teng#147]
Hello,

I recently started to use `Teng`.
And I tried to extend `Teng::Row` by the way desctibed in http://perl-users.jp/articles/advent-calendar/2011/teng/10 .
But it failed.

I wonder if it is an obsolete feature or am I wrongly use the feature.
Maybe it should be done by "base_row_class", but I didn't try this yet.

I already posted my trouble on that page. Here I post it again:

### Teng's version

0.28 (latest)

### Error Output

```
Specified column 'time2str' not found in row (query: SELECT `id`, `job_id`, `year`, `month`, `day`, `hour`, `minute`, `weekday`, `created_on`, `updated_at`
FROM `job_times`
```

### My Schema Class

```
use Teng::Schema::Declare;

table {
    name 'job_times';
    pk 'id';
    columns qw/id job_id year month day hour minute weekday created_on updated_at/;
    row_class 'Oreno::Teng::Row';
};
```

### My extended Teng::Row class

```
package Oreno::Teng::Row;

use parent 'Teng::Row';

sub time2str { ... }
```

Thanks,

**Comment by tokuhirom** [comment]
I can't reproduce your issue.
Following code works well.
```
#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use 5.010000;
use autodie;

package My::Row;
use parent qw(Teng::Row);
use HTTP::Date ();

sub strtime { HTTP::Date::time2str(shift->t) }

package My::DB::Schema;
use Teng::Schema::Declare;

table {
    name 'foo';
    columns qw/t/;
    row_class 'My::Row';
};

package My::DB;
use parent qw(Teng);

package main;

my $db = My::DB->new({ connect_info => [ 'dbi:SQLite:' ] });
$db->do('create table foo (t)');
$db->insert('foo', {
    t => time()
});
for ($db->search('foo')) {
    warn $_->strtime;
}
```

**Comment by key-amb** [comment]
Thank you for your reply.
I'll try this again soon.

**Comment by key-amb** [comment]
@tokuhirom 

Your code above worked well in my environment, too.
I think I missed something in my code.
I'll try this feature next time again.

Thank you!
